[package]
name = "euler"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
itertools = "0.13.0"
num-bigint = "0.4.6"
paste = "1.0.15"
rand = "0.9.1"
rayon = "1.10.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
